import { SYSTEM_CURRENCIES, countries } from "./config";
import {
  OpenPaydBeneficiaryType,
  IdType,
  PURPOSE_OF_TRANSACTION,
  BusinessStructure,
} from "./enums";

// Note: Type annotate this with our schema later
export const bankAccountExampleData: any[] = [
  {
    beneficiaryType: OpenPaydBeneficiaryType.RETAIL,
    firstName: "Doe",
    lastName: "John",
    dob: "1996-05-27T05:21:23.876Z",
    occupation: "Software Engineer",
    email: "johndoe@gmail.com",
    phone: "+61412345678",
    documentationType: Object.values(IdType)[0],
    idNumber: "EB123456",
    idExpiryDate: "2027-12-06T05:21:23.876Z",
    idInsurer: "Amsterdam Gov",
    purposeOfPayment: Object.keys(PURPOSE_OF_TRANSACTION)[0],
    estimatedFrequencyPerMonth: 1,
    estimatedTransactionSize: 10000,
    // Note: Bank Account
    bankAccountName: "Owner 1",
    bankAccountNumber: "10668256",
    currency: SYSTEM_CURRENCIES[1],
    country: countries.find((country) => country.code === "NL")?.code,
    address: "1st Street",
    city: "Amsterdam",
    state: "Amsterdam",
    postCode: "5555",
    bankName: "Bank of Netherlands",
    bankAddress: "2st Street",
    bankCountry: countries.find((country) => country.code === "NL")
      ?.code as string,
    bankCity: "Amsterdam",
    bankState: "Amsterdam",
    bankPostalCode: "5555",
    bankSwift: "BOSYNL2S",
    bankBranchCode: "056123",
    intermediaryBankSwift: "BOSYAU2S",
    intermediaryBankName: "Bank of Sydney",
    intermediaryBankAccountNumber: "67824567",
    intermediaryBankCountry: countries.map((country) => country.code)[0],
    intermediaryBankAddress: "10 Pitt St",
  },
  {
    beneficiaryType: OpenPaydBeneficiaryType.CORPORATE,
    businessStructure: Object.values(BusinessStructure)[0],
    registrationNumber: "51824753556",
    idExpiryDate: "2034-09-06T05:21:23.876Z",
    idInsurer: "Government of Cyprus",
    purposeOfPayment: Object.keys(PURPOSE_OF_TRANSACTION)[1],
    estimatedFrequencyPerMonth: 2,
    estimatedTransactionSize: 30000,
    // Note: Bank Account
    iban: "CY21002001950000357001234562",
    bankAccountName: "Owner 2",
    currency: SYSTEM_CURRENCIES[0],
    country: countries.find((country) => country.code === "CY")?.code,
    address: "Hippocratous 15-17",
    city: "Nicosia",
    state: "Cyprus",
    postCode: "1011",
    bankName: "Bank of Cyprus",
    bankAddress: "Hippocratous 88",
    bankCountry: countries.find((country) => country.code === "CY")
      ?.code as string,
    bankCity: "Nicosia",
    bankState: "Cyprus",
    bankPostalCode: "1011",
    bankSwift: "BCYPCY2N",
    bankBranchCode: "444444",
    bankSortCode: "222222",
  },
  {
    beneficiaryType: OpenPaydBeneficiaryType.RETAIL,
    firstName: "Dev",
    lastName: "Forexco",
    dob: "1986-01-17T05:21:23.876Z",
    occupation: "Government Officer",
    email: "forexco@example.com",
    documentationType: Object.values(IdType)[0],
    idNumber: "EB888888",
    idExpiryDate: "2017-04-06T05:21:23.876Z",
    idInsurer: "Service NSW",
    purposeOfPayment: Object.keys(PURPOSE_OF_TRANSACTION)[3],
    estimatedFrequencyPerMonth: 5,
    estimatedTransactionSize: 7300,
    // Note: Bank Account
    iban: "FR7630006000011234567890189",
    currency: SYSTEM_CURRENCIES[1],
    country: countries
      .map((country) => country.code)
      .find((code) => code === "FR"),
    address: "1st Street",
    city: "Sydney",
    state: "NSW",
    postCode: "2000",
    bankName: "Commonwealth Bank",
    bankAddress: "96 Victoria Rd, North Parramatta NSW 2151, Australia",
    bankCountry: countries
      .map((country) => country.code)
      .find((code) => code === "FR"),
    bankCity: "Sydney",
    bankState: "NSW",
    bankPostalCode: "2000",
    bankSwift: "BO",
    intermediaryBankSwift: "BOSYFR2S",
    intermediaryBankName: "Bank of France",
    intermediaryBankAccountNumber: "678",
    intermediaryBankCountry: countries
      .map((country) => country.code)
      .find((code) => code === "FR"),
    intermediaryBankAddress: "11 Pitt St",
  },
  {
    beneficiaryType: OpenPaydBeneficiaryType.RETAIL,
    firstName: "Dev",
    lastName: "Forexco",
    dob: "1986-01-17T05:21:23.876Z",
    occupation: "Government Officer",
    email: "forexco@example.com",
    documentationType: Object.values(IdType)[0],
    idNumber: "EB888888",
    idExpiryDate: "2017-04-06T05:21:23.876Z",
    idInsurer: "Service NSW",
    purposeOfPayment: Object.keys(PURPOSE_OF_TRANSACTION)[3],
    estimatedFrequencyPerMonth: 5,
    estimatedTransactionSize: 7300,
    // Note: Bank Account
    bankAccountNumber: "34562341",
    currency: SYSTEM_CURRENCIES[1],
    country: countries
      .map((country) => country.code)
      .find((code) => code === "FR"),
    address: "1st Street",
    city: "Sydney",
    state: "NSW",
    postCode: "2000",
    bankName: "Commonwealth Bank",
    bankAddress: "96 Victoria Rd, North Parramatta NSW 2151, Australia",
    bankCountry: countries
      .map((country) => country.code)
      .find((code) => code === "AU"),
    bankCity: "Sydney",
    bankState: "NSW",
    bankPostalCode: "2000",
    bankSwift: "BO",
    intermediaryBankSwift: "BOSYFR2S",
    intermediaryBankName: "Bank of France",
    intermediaryBankAccountNumber: "678",
    intermediaryBankCountry: countries
      .map((country) => country.code)
      .find((code) => code === "FR"),
    intermediaryBankAddress: "11 Pitt St",
  },
];
